name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
get:
  eva_icons_flutter: ^3.1.0
  velocity_x: ^4.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  get_storage: ^2.0.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  fluttertoast: ^8.2.6
  form_field_validator: 1.1.0
  firebase_database: ^11.0.3
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  path_provider: ^2.1.3
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  dropdown_button2: ^2.3.9
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
